// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeSettings(arg1) {
  return window['go']['backend']['App']['ChangeSettings'](arg1);
}

export function CheckCrash() {
  return window['go']['backend']['App']['CheckCrash']();
}

export function CheckCustomPolicy(arg1) {
  return window['go']['backend']['App']['CheckCustomPolicy'](arg1);
}

export function CheckCustomPolicyModifier(arg1) {
  return window['go']['backend']['App']['CheckCustomPolicyModifier'](arg1);
}

export function ExitProgram() {
  return window['go']['backend']['App']['ExitProgram']();
}

export function FileDialog(arg1) {
  return window['go']['backend']['App']['FileDialog'](arg1);
}

export function GetCategories() {
  return window['go']['backend']['App']['GetCategories']();
}

export function GetServiceNames() {
  return window['go']['backend']['App']['GetServiceNames']();
}

export function InitializeConfig() {
  return window['go']['backend']['App']['InitializeConfig']();
}

export function RestartApplication() {
  return window['go']['backend']['App']['RestartApplication']();
}

export function RunPasswordAnalysis(arg1) {
  return window['go']['backend']['App']['RunPasswordAnalysis'](arg1);
}

export function RunPasswordModifier(arg1, arg2, arg3) {
  return window['go']['backend']['App']['RunPasswordModifier'](arg1, arg2, arg3);
}

export function RunPasswordValidator(arg1, arg2, arg3) {
  return window['go']['backend']['App']['RunPasswordValidator'](arg1, arg2, arg3);
}

export function RunSmartFilter(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['RunSmartFilter'](arg1, arg2, arg3, arg4, arg5);
}

export function ShowTutorial() {
  return window['go']['backend']['App']['ShowTutorial']();
}

export function TutorialCompleted() {
  return window['go']['backend']['App']['TutorialCompleted']();
}
