// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utilities} from '../models';
import {passwordAnalysis} from '../models';
import {passwordModifier} from '../models';
import {passwordValidator} from '../models';

export function ChangeSettings(arg1:utilities.Settings):Promise<void>;

export function CheckCrash():Promise<boolean>;

export function CheckCustomPolicy(arg1:string):Promise<boolean>;

export function CheckCustomPolicyModifier(arg1:string):Promise<boolean>;

export function ExitProgram():Promise<void>;

export function FileDialog(arg1:string):Promise<string>;

export function GetCategories():Promise<Array<string>>;

export function GetServiceNames():Promise<Array<string>>;

export function InitializeConfig():Promise<utilities.Settings>;

export function RestartApplication():Promise<void>;

export function RunPasswordAnalysis(arg1:string):Promise<passwordAnalysis.Result>;

export function RunPasswordModifier(arg1:string,arg2:string,arg3:string):Promise<passwordModifier.Output>;

export function RunPasswordValidator(arg1:string,arg2:string,arg3:string):Promise<passwordValidator.Output>;

export function RunSmartFilter(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<Array<string>>;

export function ShowTutorial():Promise<boolean>;

export function TutorialCompleted():Promise<void>;
